name: send_sms

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 7 * * *"

jobs:
  send_sms:
    runs-on: ubuntu-latest
    env:
      TEXT_API_KEY: ${{ secrets.TEXT_API_KEY }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install required packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests python-dotenv
      - name: Run Python script
        run: |
          cd $GITHUB_WORKSPACE
          python send_sms.py
